### PR TITLE
ALTAPPS-550: Support SQL quiz on Android

### PR DESCRIPTION
**Pull request by XanderZhu**
**YouTrack Issues**:
[#ALTAPPS-550](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-550/Android-Support-SQL-quiz)

**Checklist**

_Before Code Review:_

- [x] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [x] All checks have been passed;
- [x] Changes have been checked locally.

**Description**
- Add SqlStepQuizFormDelegate and SqlStepQuizFragment
***Update:***
- Fix redundant keyboard messages sending from Sql and Code quiz ui
- Refactor StepQuiz buttons rendering

### CODE REVIEW

**Review by ivan-magda — CHANGES_REQUESTED** [review]
1. When opening a code problem now "Input & Output Info" is not visible

 

2. The code editor preview doesn't have a top separator

 

3. Not shows the submission error state and feedback

 

4. Reset button is not working



5. Incorrect title for the fullscreen code editor, should be "Write an SQL statement"



6. Unneseccary separator in the details tab of the fullscreen code editor

**Review by ivan-magda — CHANGES_REQUESTED** [review]
1. Please merge the `develop` branch and update `BlockName.supportedBlocksNames` to include `SQL` on Android.
2. I'm still encountering a problem with "Not shows the submission error state and feedback". 

Please see the screencast

https://user-images.githubusercontent.com/8586063/216316799-3e0565ca-04fa-4463-8d5f-4552c17e9e50.mp4

**Comment by XanderZhu** [comment]
@ivan-magda 
Could you please tell me id of the task you are testing on?

**Comment by ivan-magda** [comment]
> @ivan-magda
> Could you please tell me id of the task you are testing on?

`step_id=9091`

**Review by ivan-magda — CHANGES_REQUESTED** [review]
Something wrong with the code reset. In the `develop` branch code resets to the template, but here to empty. I suppose when `submission?.reply?.code == null` we need to use a code template.


`develop, step_id = 4584`

https://user-images.githubusercontent.com/8586063/216749198-656bb622-c58e-4333-bdb0-2f302fb398f2.mp4

current


https://user-images.githubusercontent.com/8586063/216749218-c196ea5d-8987-4d16-a968-520693d79e2a.mp4

**Review by ivan-magda — APPROVED** [review]

**Pull request merged**
