### PR TITLE
ALTAPPS-778: Android add track selection details track overview layout

### PR DESCRIPTION
**Pull request by vladkash**
**YouTrack Issues**:
[#ALTAPPS-778](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-778)

**Checklist**

_Before Code Review:_

- [x] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [x] All checks have been passed;
- [x] Changes have been checked locally.

**Description**
- Added `layout_track_selection_details_track_overview.xml` and necessary icons

### CODE REVIEW

**Comment by vladkash** [comment]
@Xanderzhou the problem I faced is aligning icons with different paddings after export, could you help me with suggestion how can I fix it?
Screenshot 2023-05-23 at 11 49 37

**Comment by XanderZhu** [comment]
@vladkash 
> the problem I faced is aligning icons with different paddings after export, could you help me with suggestion how can I fix it?

Basically, you should export icons from Figma without paddings. Usually, there are few containers over icons. Choose the one without paddings.

**Comment by vladkash** [comment]
@XanderZhu Now it seems better, the design is a little bit difficult to implement - icons have different sizes and it breakes alignment
image

**Comment by XanderZhu** [comment]
@vladkash 
> icons have different sizes and it breakes alignment

Visually I don't see any alignment issues in the new version. Seems good.
If the existing icons have different sizes, you can create a duplication of the icon with the proper size.

**Comment by ivan-magda** [comment]
> @vladkash
> 
> > icons have different sizes and it breakes alignment
> 
> Visually I don't see any alignment issues in the new version. Seems good. If the existing icons have different sizes, you can create a duplication of the icon with the proper size.

the text should be centered vertically

240201355-488f4e3f-b663-4494-bd88-df562e76bf91

**Review by XanderZhu — APPROVED** [review]

**Pull request merged**
