### PR TITLE
ALTAPPS-643: Shared handle rejected submission feedback

### PR DESCRIPTION
**Pull request by ivan-magda**
**YouTrack Issues**:
[#ALTAPPS-643](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-643)

**Checklist**

_Before Code Review:_

- [x] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [x] All checks have been passed;
- [x] Changes have been checked locally.

**Description**
- Adds support to Submission.feedback either as a string and as an object with title and message

### CODE REVIEW

**Comment by ivan-magda** [comment]
@XanderZhu please add the necessary changes for the Android part

Links:
1. https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-643/Shared-Add-default-serialization-value-for-submission-status#focus=Comments-74-220933.0-0
1. https://vyahhi.myjetbrains.com/youtrack/issue/ALT-8571/Update-error-limit-is-reached-in-the-API-Submissions#focus=Comments-74-220996.0-0

**Comment by XanderZhu** [comment]
@ivan-magda 
Is it OK, thar backend send a feedback as s string at the moment? 
It could not be parsed now.

**Review by XanderZhu — APPROVED** [review]

**Comment by ivan-magda** [comment]
> @ivan-magda 
> 
> Is it OK, thar backend send a feedback as s string at the moment? 
> 
> It could not be parsed now.

Backend can serialize feedback in two formats: plain string or object. How feedback will be serialized depends on many circumstances.

For now we just handle submission rejected feedback.

**Comment by XanderZhu** [comment]
@ivan-magda 
If I got you right, `Submission.feedback` could be either String or object, just the same as [Feedback interface](https://github.com/hyperskill/mobile-app/blob/822f8fcc113e020f79dce259c2a0941a6d9204d4/shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/model/submissions/Feedback.kt#L9-L19), right?

**Comment by ivan-magda** [comment]
> @ivan-magda 
> 
> If I got you right, [FeedbackRejectedSubmission](https://github.com/hyperskill/mobile-app/blob/822f8fcc113e020f79dce259c2a0941a6d9204d4/shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/model/submissions/Feedback.kt#L21-L27) could be either String or object, just the same as [Feedback interface](https://github.com/hyperskill/mobile-app/blob/822f8fcc113e020f79dce259c2a0941a6d9204d4/shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/model/submissions/Feedback.kt#L9-L19), right?

No, rejected submission is only an object https://vyahhi.myjetbrains.com/youtrack/issue/ALT-8571/Update-error-limit-is-reached-in-the-API-Submissions#focus=Comments-74-220996.0-0

**Pull request merged**
