### PR TITLE
ALTAPPS-811: Support Android 13

### PR DESCRIPTION
**Pull request by XanderZhu**
**YouTrack Issues**:
[#ALTAPPS-811](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-811)

**Checklist**

_Before Code Review:_

- [X] Fields "Assignees, Labels, Milestone" are filled in the pull request;
- [x] All checks have been passed;
- [X] Changes have been checked locally.

**Description**
- Update targetSdk to 33
- Support PostNotification permission request in Profile & StepQuiz

### CODE REVIEW

**Review by ivan-magda — APPROVED** [review]
Do you want to release this in `1.25` or later in `1.26`?

**Comment by XanderZhu** [comment]
@ivan-magda 
It's better to release it in 1.26.

**Comment by XanderZhu** [comment]
@ivan-magda 
So, to not release this PR in 1.25 it should not be merged into develop, until the release of 1.25, right?

**Comment by ivan-magda** [comment]
> @ivan-magda
> So, to not release this PR in 1.25 it should not be merged into develop, until the release of 1.25, right?

It depends:
1. we can merge this PR to the `develop` right now and cherry-pick necessary to 1.25 if needed
2. or as you said wait for release 1.25

notify later about what you choose

**Comment by XanderZhu** [comment]
@ivan-magda 
Let's wait for release 1.25

**Pull request merged**
